import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/* =========================================================
   CONSTANTS & THEME
   ========================================================= */
const COLORS = {
  primary: [79, 70, 229], // Indigo-600
  secondary: [100, 116, 139], // Slate-500
  text: [30, 41, 59], // Slate-800
  lightBg: [248, 250, 252], // Slate-50
  accent: [245, 158, 11], // Amber (Donations)
  danger: [220, 38, 38], // Red (Expenses)
  success: [16, 185, 129], // Emerald (Collections)
};

// 👇 PASTE YOUR LOGO BASE64 STRING HERE
const LOGO_BASE64 = ""; 

// Helper: Title Case
const toTitleCase = (str) => {
  return String(str || "")
    .toLowerCase()
    .split(" ")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

const sanitizeName = (s) => String(s || "").trim().replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "");

function formatCurrency(n) {
  return `Rs. ${Number(n || 0).toLocaleString("en-IN")}`;
}

/* ---------------------------------------------------------
   MODERN HEADER COMPONENT
   --------------------------------------------------------- */
const drawHeader = (doc, clubName, reportTitle, subtitle = "") => {
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  
  // 1. Top Decorative Line
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 4, "F");

  // --- LOGO & BRAND SECTION (TOP RIGHT) ---
  const logoSize = 12; 
  const logoY = 10; 
  const logoX = pageWidth - margin - 20; 
  const centerX = logoX + (logoSize / 2); 

  if (LOGO_BASE64) {
      try {
        doc.addImage(LOGO_BASE64, "PNG", logoX, logoY, logoSize, logoSize);
      } catch (e) {
        console.error("Logo Error", e);
      }
  } else {
      doc.setFillColor(...COLORS.primary);
      doc.roundedRect(logoX, logoY, logoSize, logoSize, 2.5, 2.5, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text("CK", centerX, logoY + 7.5, { align: "center" });
  }

  // --- BRAND NAME ---
  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(14); 
  doc.setFont("helvetica", "bold");
  doc.text("ClubKhata", centerX, logoY + logoSize + 6, { align: "center" });

  // --- REPORT TITLES ---
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.text);
  doc.setFont("helvetica", "bold");
  doc.text(toTitleCase(clubName || "Club Committee"), margin, 20);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.primary);
  doc.setFont("helvetica", "bold");
  doc.text(reportTitle.toUpperCase(), margin, 28);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.secondary);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, margin, 35);
  }

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, 42, pageWidth - margin, 42);

  return 50; 
};

const drawFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.secondary);
    doc.text(`Generated by ClubKhata • ${new Date().toLocaleDateString()}`, 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: "right" });
  }
};

/* =========================================================
   1. HISTORY EXPORT (FIXED: Footer only on last page)
   ========================================================= */
export const exportHistoryCyclePDF = ({
  cycle,
  summary,
  weekly,
  puja,
  donations,
  expenses,
  clubName,
  frequency = "weekly",
}) => {
  const doc = new jsPDF();
  const margin = 14;
  
  const cycleDate = `${new Date(cycle.startDate).toLocaleDateString('en-IN')} - ${new Date(cycle.endDate).toLocaleDateString('en-IN')}`;
  let y = drawHeader(doc, clubName, "Financial History Report", `Cycle: ${cycle.name} | ${cycleDate}`);

  // --- SUMMARY TABLE ---
  autoTable(doc, {
    startY: y,
    head: [["Opening", "Collections", "Expenses", "Closing"]],
    body: [[
      formatCurrency(summary.openingBalance),
      formatCurrency(summary.collections),
      formatCurrency(summary.expenses),
      formatCurrency(summary.closingBalance),
    ]],
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, halign: 'center', fontStyle: 'bold' },
    bodyStyles: { halign: 'center', fontStyle: 'bold', textColor: COLORS.text, minCellHeight: 12, valign: 'middle' },
    margin: { left: margin, right: margin }
  });

  y = doc.lastAutoTable.finalY + 20; 

  // --- SECTIONS HELPER ---
  const addSection = (title, head, body, color, totalValue) => {
    if (y + 35 > 280) { 
      doc.addPage(); 
      y = 20; 
    }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.text);
    doc.setFont(undefined, "bold");
    
    doc.text(title, margin, y + 4); 
    
    // Footer Logic
    const footRow = ["Total"];
    for (let i = 1; i < head.length - 1; i++) footRow.push("");
    footRow.push(formatCurrency(totalValue));

    autoTable(doc, {
      startY: y + 8,
      head: [head],
      body: body,
      foot: [footRow],
      // ✅ FIX: Only show footer on the last page of the table
      showFoot: 'lastPage',
      theme: "striped",
      headStyles: { fillColor: color },
      footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold', halign: 'right' },
      columnStyles: { 
          [head.length - 1]: { halign: "right", fontStyle: "bold" },
          0: { halign: 'left' }
      },
      didParseCell: function(data) {
          if (data.section === 'foot' && data.column.index === 0) {
              data.cell.styles.halign = 'left';
          }
      },
      margin: { left: margin, right: margin }
    });
    
    y = doc.lastAutoTable.finalY + 15;
  };

  if (weekly?.length) {
    const totalWeekly = weekly.reduce((sum, w) => sum + (Number(w.total) || 0), 0);
    const subLabel = frequency === "monthly" ? "Monthly Contributions" : "Weekly Contributions";
    addSection(subLabel, ["Member Name", "Amount"], weekly.map(w => [w.memberName, formatCurrency(w.total)]), COLORS.primary, totalWeekly);
  }

  if (puja?.length) {
    const totalPuja = puja.reduce((sum, p) => sum + (Number(p.total) || 0), 0);
    addSection("Puja Contributions", ["Member Name", "Amount"], puja.map(p => [p.memberName, formatCurrency(p.total)]), COLORS.success, totalPuja);
  }

  if (donations?.length) {
    const totalDonations = donations.reduce((sum, d) => sum + (Number(d.amount) || 0), 0);
    addSection("Donations", ["Donor", "Date", "Amount"], donations.map(d => [d.donorName, new Date(d.date).toLocaleDateString('en-IN'), formatCurrency(d.amount)]), COLORS.accent, totalDonations);
  }

  if (expenses?.length) {
    const totalExpenses = expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);
    addSection("Expenses Breakdown", ["Title", "Date", "Amount"], expenses.map(e => [e.title, new Date(e.date).toLocaleDateString('en-IN'), formatCurrency(e.amount)]), COLORS.danger, totalExpenses);
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Archive_${sanitizeName(cycle.name)}.pdf`);
};

/* =========================================================
   2. FINANCE EXPORT
   ========================================================= */
export const exportFinancePDF = ({
  clubName = "Club",
  summary,
  contributions,
  expenses,
}) => {
  const doc = new jsPDF();
  let y = drawHeader(doc, clubName, "Financial Snapshot", "Current Status Overview");

  doc.setFontSize(11); doc.setTextColor(...COLORS.secondary); doc.text("SUMMARY", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Category", "Amount"]],
    body: summary.map((s) => [s.label, formatCurrency(s.value)]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 15;

  const totalContributions = contributions.reduce((sum, c) => sum + (Number(c.amount) || 0), 0);
  doc.text("CONTRIBUTIONS BREAKDOWN", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Source", "Total Amount"]],
    body: contributions.map((c) => [c.type, formatCurrency(c.amount)]),
    foot: [["Total", formatCurrency(totalContributions)]],
    showFoot: 'lastPage', // ✅ FIX
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 15;

  if (expenses?.length) {
    const totalExpenses = expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);
    doc.text("RECENT EXPENSES", 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [["Title", "Status", "Amount"]],
      body: expenses.map((e) => [e.title, e.status.toUpperCase(), formatCurrency(e.amount)]),
      foot: [["Total", "", formatCurrency(totalExpenses)]],
      showFoot: 'lastPage', // ✅ FIX
      theme: "striped",
      headStyles: { fillColor: COLORS.danger },
      footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
      columnStyles: { 2: { halign: "right", fontStyle: "bold" } }
    });
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Finance_Snapshot.pdf`);
};

/* =========================================================
   3. DONATIONS EXPORT
   ========================================================= */
export const exportDonationsPDF = ({ clubName, cycleName, donations = [] }) => {
  const doc = new jsPDF();
  const total = (donations || []).reduce((s, d) => s + Number(d.amount || 0), 0);
  
  let y = drawHeader(doc, clubName, "Donation Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.accent);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Receipt No", "Donor Name", "Contact", "Amount"]],
    body: donations.map((d) => [
      new Date(d.date).toLocaleDateString('en-IN'),
      d.receiptNo || "-",
      d.donorName || "-",
      d.phone || d.address || "-",
      formatCurrency(d.amount),
    ]),
    foot: [["Total", "", "", "", formatCurrency(total)]],
    showFoot: 'lastPage', // ✅ FIX
    theme: "striped",
    headStyles: { fillColor: COLORS.accent },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Donations.pdf`);
};

/* =========================================================
   4. EXPENSES EXPORT
   ========================================================= */
export const exportExpensesPDF = ({ clubName, cycleName, expenses }) => {
  const doc = new jsPDF();
  const totalApproved = expenses
    .filter(e => e.status === "approved")
    .reduce((sum, e) => sum + Number(e.amount || 0), 0);

  let y = drawHeader(doc, clubName, "Expenses Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.danger);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Approved: ${formatCurrency(totalApproved)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Title", "Category", "Recorded By", "Status", "Amount"]],
    body: expenses.map((e) => [
      new Date(e.date).toLocaleDateString('en-IN'),
      e.title,
      e.category,
      e.recordedBy?.name || "-",
      e.status.toUpperCase(),
      formatCurrency(e.amount),
    ]),
    foot: [["Total", "", "", "", "", formatCurrency(totalApproved)]],
    showFoot: 'lastPage', // ✅ FIX
    theme: "striped",
    headStyles: { fillColor: COLORS.danger },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 
        5: { halign: "right", fontStyle: "bold" },
        4: { fontSize: 8, fontStyle: "bold" }
    },
    didParseCell: function(data) {
        if (data.column.index === 4 && data.section === 'body') {
            const status = data.cell.raw;
            if (status === 'APPROVED') data.cell.styles.textColor = [22, 163, 74]; 
            else if (status === 'REJECTED') data.cell.styles.textColor = [220, 38, 38];
            else data.cell.styles.textColor = [217, 119, 6]; 
        }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Expenses.pdf`);
};

/* =========================================================
   5. PUJA EXPORT
   ========================================================= */
export const exportPujaPDF = ({ clubName, cycleName, data }) => {
  const doc = new jsPDF();
  const total = data.reduce((sum, row) => sum + Number(row.amount || 0), 0);

  let y = drawHeader(doc, clubName, "Festival Chanda Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.success);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Member Name", "Notes", "Amount"]],
    body: data.map((row) => [
      new Date(row.createdAt).toLocaleDateString('en-IN'),
      row.user?.name || "Unknown",
      row.notes || "-",
      formatCurrency(row.amount),
    ]),
    foot: [["Total", "", "", formatCurrency(total)]],
    showFoot: 'lastPage', // ✅ FIX
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 3: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Puja_Chanda.pdf`);
};

/* =========================================================
   6. MEMBERS EXPORT
   ========================================================= */
export const exportMembersPDF = ({ clubName, members }) => {
  const doc = new jsPDF();
  
  let y = drawHeader(doc, clubName, "Member Directory", `Total Members: ${members.length}`);

  autoTable(doc, {
    startY: y,
    head: [["#", "Name", "Role", "Phone", "Email", "Joined"]],
    body: members.map((m, index) => [
      index + 1,
      m.name,
      m.role.toUpperCase(),
      m.phone || "-",
      m.email,
      new Date(m.joinedAt).toLocaleDateString('en-IN')
    ]),
    theme: "striped",
    headStyles: { fillColor: COLORS.primary },
    columnStyles: { 
      0: { halign: "center", fontStyle: "bold", cellWidth: 10 },
      2: { fontStyle: "bold", fontSize: 8 },
    },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Members_List.pdf`);
};

/* =========================================================
   7. AUDIT LOGS EXPORT
   ========================================================= */
export const exportAuditLogsPDF = ({ clubName, logs, period }) => {
  const doc = new jsPDF();
  
  let y = drawHeader(doc, clubName, "Audit Logs", period ? `Period: ${period}` : "");

  autoTable(doc, {
    startY: y,
    head: [["Date", "Time", "Actor", "Action", "Target", "Details"]],
    body: logs.map((log) => {
        let detailsStr = "-";
        if (log.details) {
             detailsStr = Object.entries(log.details)
                .filter(([k]) => !['_id', 'club', 'userId', 'memberId', 'expenseId'].includes(k))
                .map(([k, v]) => {
                    const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
                    return `${label}: ${v}`;
                })
                .join('\n');
        }

        return [
          new Date(log.createdAt).toLocaleDateString('en-IN'),
          new Date(log.createdAt).toLocaleTimeString(),
          log.actor?.name || "System",
          log.action?.replace(/_/g, ' ') || "-",
          log.target || "-",
          detailsStr
        ];
    }),
    theme: "grid",
    headStyles: { fillColor: COLORS.secondary }, 
    styles: { fontSize: 8, cellPadding: 2, valign: 'middle' },
    columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 18 },
        2: { cellWidth: 25, fontStyle: "bold" },
        5: { fontSize: 7 }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_AuditLogs.pdf`);
};