import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/* =========================================================
   CONSTANTS & HELPERS
   ========================================================= */
const COLORS = {
  primary: [79, 70, 229], // Indigo-600
  secondary: [100, 116, 139], // Slate-500
  text: [30, 41, 59], // Slate-800
  accent: [245, 158, 11], // Amber (for donations)
  danger: [220, 38, 38], // Red (for expenses)
  success: [16, 185, 129], // Emerald (for collections)
};

const sanitizeName = (s) => String(s || "").trim().replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "");

function formatCurrency(n) {
  return `Rs. ${Number(n || 0).toLocaleString("en-IN")}`;
}

/* ---------------------------------------------------------
   MODERN HEADER COMPONENT
   Draws Club Name, App Logo, Report Title, and Metadata
   --------------------------------------------------------- */
const drawHeader = (doc, clubName, reportTitle, subtitle = "") => {
  const pageWidth = doc.internal.pageSize.width;
  
  // 1. Top Decorative Line (Indigo)
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 4, "F");

  // 2. App Branding (Top Right) -> "● ClubKhata"
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.primary);
  doc.setFont(undefined, "bold");
  
  // Draw Circle Icon
  doc.setFillColor(...COLORS.primary);
  doc.circle(pageWidth - 38, 14, 1.5, "F"); 
  
  // Draw App Name
  doc.text("ClubKhata", pageWidth - 34, 15);

  // 3. Club Name (Main Title - Left)
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.text);
  doc.setFont("helvetica", "bold");
  doc.text(clubName || "Club Committee", 14, 20);

  // 4. Report Title (Subtitle - Left)
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.secondary);
  doc.setFont("helvetica", "normal");
  doc.text(reportTitle.toUpperCase(), 14, 28);

  // 5. Metadata/Subtitle (e.g., Date/Cycle)
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(subtitle, 14, 35);
  }

  // 6. Divider Line
  doc.setDrawColor(230);
  doc.setLineWidth(0.5);
  doc.line(14, 40, pageWidth - 14, 40);

  return 45; // Return Y position to start content
};

/* ---------------------------------------------------------
   MODERN FOOTER COMPONENT
   Adds "Generated by ClubKhata" and Page Numbers
   --------------------------------------------------------- */
const drawFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    
    // Left: Generated Text
    doc.text(`Generated by ClubKhata Financial Manager • ${new Date().toLocaleDateString()}`, 14, pageHeight - 10);
    
    // Right: Page Number
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: "right" });
  }
};

/* =========================================================
   1. HISTORY EXPORT (Detailed)
   ========================================================= */
export const exportHistoryCyclePDF = ({
  cycle,
  summary,
  weekly,
  puja,
  donations,
  expenses,
  clubName,
}) => {
  const doc = new jsPDF();
  
  const cycleDate = `${new Date(cycle.startDate).toLocaleDateString()} - ${new Date(cycle.endDate).toLocaleDateString()}`;
  let y = drawHeader(doc, clubName, "Financial History Report", `Cycle: ${cycle.name} | ${cycleDate}`);

  // --- SUMMARY TABLE ---
  autoTable(doc, {
    startY: y,
    head: [["Opening", "Collections", "Expenses", "Closing"]],
    body: [[
      formatCurrency(summary.openingBalance),
      formatCurrency(summary.collections),
      formatCurrency(summary.expenses),
      formatCurrency(summary.closingBalance),
    ]],
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, halign: 'center' },
    bodyStyles: { halign: 'center', fontStyle: 'bold' },
  });

  y = doc.lastAutoTable.finalY + 15;

  // --- SECTIONS HELPER ---
  const addSection = (title, head, body, color) => {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setTextColor(...COLORS.text);
    doc.setFont(undefined, "bold");
    doc.text(title, 14, y);
    
    autoTable(doc, {
      startY: y + 3,
      head: [head],
      body: body,
      theme: "striped",
      headStyles: { fillColor: color },
      columnStyles: { [head.length - 1]: { halign: "right", fontStyle: "bold" } } // Last col right aligned
    });
    y = doc.lastAutoTable.finalY + 10;
  };

  if (weekly?.length) {
    addSection("Weekly Contributions", ["Member Name", "Amount"], weekly.map(w => [w.memberName, formatCurrency(w.total)]), COLORS.primary);
  }

  if (puja?.length) {
    addSection("Puja Contributions", ["Member Name", "Amount"], puja.map(p => [p.memberName, formatCurrency(p.total)]), COLORS.success);
  }

  if (donations?.length) {
    addSection("Donations", ["Donor", "Date", "Amount"], donations.map(d => [d.donorName, d.date, formatCurrency(d.amount)]), COLORS.accent);
  }

  if (expenses?.length) {
    addSection("Expenses Breakdown", ["Title", "Date", "Amount"], expenses.map(e => [e.title, e.date, formatCurrency(e.amount)]), COLORS.danger);
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_History_${sanitizeName(cycle.name)}.pdf`);
};

/* =========================================================
   2. FINANCE EXPORT (Snapshot)
   ========================================================= */
export const exportFinancePDF = ({
  clubName = "Club",
  summary,
  contributions,
  expenses,
}) => {
  const doc = new jsPDF();
  let y = drawHeader(doc, clubName, "Financial Snapshot", "Current Status Overview");

  doc.setFontSize(12); doc.setTextColor(...COLORS.text); doc.text("Summary", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Category", "Amount"]],
    body: summary.map((s) => [s.label, formatCurrency(s.value)]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 12;

  doc.text("Contributions Overview", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Source", "Total Amount"]],
    body: contributions.map((c) => [c.type, formatCurrency(c.amount)]),
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 12;

  if (expenses?.length) {
    doc.text("Recent Expenses", 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [["Title", "Status", "Amount"]],
      body: expenses.map((e) => [e.title, e.status, formatCurrency(e.amount)]),
      theme: "striped",
      headStyles: { fillColor: COLORS.danger },
      columnStyles: { 2: { halign: "right", fontStyle: "bold" } }
    });
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Finance_Snapshot.pdf`);
};

/* =========================================================
   3. DONATIONS LIST EXPORT
   ========================================================= */
export const exportDonationsPDF = ({ clubName, cycleName, donations = [] }) => {
  const doc = new jsPDF();
  const total = (donations || []).reduce((s, d) => s + (d.amount || 0), 0);
  
  let y = drawHeader(doc, clubName, "Donation Report", `Cycle: ${cycleName || "N/A"}`);

  // Total Badge
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.accent);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Receipt No", "Donor Name", "Contact", "Amount"]],
    body: donations.map((d) => [
      new Date(d.date).toLocaleDateString(),
      d.receiptNo || "-",
      d.donorName || "-",
      d.phone || d.address || "-",
      formatCurrency(d.amount),
    ]),
    theme: "striped",
    headStyles: { fillColor: COLORS.accent },
    columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Donations.pdf`);
};

/* =========================================================
   4. EXPENSES LIST EXPORT
   ========================================================= */
export const exportExpensesPDF = ({ clubName, cycleName, expenses }) => {
  const doc = new jsPDF();
  const totalApproved = expenses
    .filter(e => e.status === "approved")
    .reduce((sum, e) => sum + e.amount, 0);

  let y = drawHeader(doc, clubName, "Expenses Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.danger);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Approved: ${formatCurrency(totalApproved)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Title", "Category", "Recorded By", "Status", "Amount"]],
    body: expenses.map((e) => [
      new Date(e.date).toLocaleDateString(),
      e.title,
      e.category,
      e.recordedBy?.name || "-",
      e.status.toUpperCase(),
      formatCurrency(e.amount),
    ]),
    theme: "striped",
    headStyles: { fillColor: COLORS.danger },
    columnStyles: { 
        5: { halign: "right", fontStyle: "bold" },
        4: { fontSize: 8, fontStyle: "bold" }
    },
    didParseCell: function(data) {
        if (data.column.index === 4 && data.section === 'body') {
            const status = data.cell.raw;
            if (status === 'APPROVED') data.cell.styles.textColor = [22, 163, 74]; 
            else if (status === 'REJECTED') data.cell.styles.textColor = [220, 38, 38];
            else data.cell.styles.textColor = [217, 119, 6]; 
        }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Expenses.pdf`);
};

/* =========================================================
   5. PUJA CONTRIBUTIONS EXPORT
   ========================================================= */
export const exportPujaPDF = ({ clubName, cycleName, data }) => {
  const doc = new jsPDF();
  const total = data.reduce((sum, row) => sum + row.amount, 0);

  let y = drawHeader(doc, clubName, "Festival Chanda Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.success);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Member Name", "Notes", "Amount"]],
    body: data.map((row) => [
      new Date(row.createdAt).toLocaleDateString(),
      row.user?.name || "Unknown",
      row.notes || "-",
      formatCurrency(row.amount),
    ]),
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    columnStyles: { 3: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Puja_Chanda.pdf`);
};

/* =========================================================
   6. MEMBERS LIST EXPORT
   ========================================================= */
export const exportMembersPDF = ({ clubName, members }) => {
  const doc = new jsPDF();
  
  let y = drawHeader(doc, clubName, "Member Directory", `Total Members: ${members.length}`);

  autoTable(doc, {
    startY: y,
    head: [["#", "Name", "Role", "Phone", "Email", "Joined"]],
    body: members.map((m, index) => [
      index + 1,
      m.name,
      m.role.toUpperCase(),
      m.phone || "-",
      m.email,
      new Date(m.joinedAt).toLocaleDateString()
    ]),
    theme: "striped",
    headStyles: { fillColor: COLORS.primary },
    columnStyles: { 
      0: { halign: "center", fontStyle: "bold", cellWidth: 10 },
      2: { fontStyle: "bold", fontSize: 8 },
    },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Members_List.pdf`);
};

/* =========================================================
   7. AUDIT LOGS EXPORT
   ========================================================= */
export const exportAuditLogsPDF = ({ clubName, logs, period }) => {
  const doc = new jsPDF();
  
  let y = drawHeader(doc, clubName, "Audit Logs", period ? `Period: ${period}` : "");

  autoTable(doc, {
    startY: y,
    head: [["Date", "Time", "Actor", "Action", "Target", "Details"]],
    body: logs.map((log) => {
        let detailsStr = "-";
        if (log.details) {
             detailsStr = Object.entries(log.details)
                .filter(([k]) => !['_id', 'club', 'userId', 'memberId', 'expenseId'].includes(k))
                .map(([k, v]) => {
                    const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
                    return `${label}: ${v}`;
                })
                .join('\n');
        }

        return [
          new Date(log.createdAt).toLocaleDateString(),
          new Date(log.createdAt).toLocaleTimeString(),
          log.actor?.name || "System",
          log.action?.replace(/_/g, ' ') || "-",
          log.target || "-",
          detailsStr
        ];
    }),
    theme: "grid",
    headStyles: { fillColor: [71, 85, 105] }, // Slate-700
    styles: { fontSize: 8, cellPadding: 2, valign: 'middle' },
    columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 18 },
        2: { cellWidth: 25, fontStyle: "bold" },
        5: { fontSize: 7 }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_AuditLogs.pdf`);
};