import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/* =========================================================
   CONSTANTS & THEME
   ========================================================= */
const COLORS = {
  primary: [79, 70, 229], // Indigo-600
  secondary: [100, 116, 139], // Slate-500
  text: [30, 41, 59], // Slate-800
  lightBg: [248, 250, 252], // Slate-50
  accent: [245, 158, 11], // Amber (Donations)
  danger: [220, 38, 38], // Red (Expenses)
  success: [16, 185, 129], // Emerald (Collections)
};

// Helper: Title Case (e.g. "happy club" -> "Happy Club")
const toTitleCase = (str) => {
  return String(str || "")
    .toLowerCase()
    .split(" ")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

const sanitizeName = (s) => String(s || "").trim().replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "");

// Helper: Ensure input is treated as a number before formatting
function formatCurrency(n) {
  return `Rs. ${Number(n || 0).toLocaleString("en-IN")}`;
}

/* ---------------------------------------------------------
   MODERN HEADER COMPONENT
   --------------------------------------------------------- */
const drawHeader = (doc, clubName, reportTitle, subtitle = "") => {
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;
  
  // 1. Top Decorative Line
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 4, "F");

  // 2. App Branding (Top Right)
  const logoSize = 10;
  const logoY = 12;
  const logoX = pageWidth - margin - 35; 

  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(logoX, logoY, logoSize, logoSize, 2.5, 2.5, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("CK", logoX + (logoSize / 2), logoY + 6.5, { align: "center" });

  doc.setTextColor(...COLORS.primary);
  doc.setFontSize(12);
  doc.text("ClubKhata", logoX + logoSize + 4, logoY + 6.5);

  // 3. Club Name (Title Case)
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.text);
  doc.setFont("helvetica", "bold");
  doc.text(toTitleCase(clubName || "Club Committee"), margin, 20);

  // 4. Report Title
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.primary);
  doc.setFont("helvetica", "bold");
  doc.text(reportTitle.toUpperCase(), margin, 28);

  // 5. Subtitle
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.secondary);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, margin, 35);
  }

  // 6. Divider Line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, 42, pageWidth - margin, 42);

  return 50; 
};

const drawFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.secondary);
    doc.text(`Generated by ClubKhata • ${new Date().toLocaleDateString()}`, 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: "right" });
  }
};

/* =========================================================
   1. HISTORY EXPORT (Detailed)
   ========================================================= */
export const exportHistoryCyclePDF = ({
  cycle,
  summary,
  weekly,
  puja,
  donations,
  expenses,
  clubName,
  frequency = "weekly",
}) => {
  const doc = new jsPDF();
  const margin = 14;
  
  const cycleDate = `${new Date(cycle.startDate).toLocaleDateString()} - ${new Date(cycle.endDate).toLocaleDateString()}`;
  let y = drawHeader(doc, clubName, "Financial History Report", `Cycle: ${cycle.name} | ${cycleDate}`);

  // --- SUMMARY TABLE ---
  autoTable(doc, {
    startY: y,
    head: [["Opening", "Collections", "Expenses", "Closing"]],
    body: [[
      formatCurrency(summary.openingBalance),
      formatCurrency(summary.collections),
      formatCurrency(summary.expenses),
      formatCurrency(summary.closingBalance),
    ]],
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, halign: 'center', fontStyle: 'bold' },
    bodyStyles: { halign: 'center', fontStyle: 'bold', textColor: COLORS.text, minCellHeight: 12, valign: 'middle' },
    margin: { left: margin, right: margin }
  });

  y = doc.lastAutoTable.finalY + 20; 

  // --- SECTIONS HELPER ---
  // Updated to accept 'totalValue'
  const addSection = (title, head, body, color, totalValue) => {
    // Page Break Check
    if (y + 35 > 280) { 
      doc.addPage(); 
      y = 20; 
    }

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.text);
    doc.setFont(undefined, "bold");
    
    // Title Text (Aligned to margin)
    doc.text(title, margin, y + 4); 
    
    // Construct Footer Row for Total
    // Logic: "Total" in first col, empty strings for middle cols, Value in last col
    const footRow = ["Total"];
    for (let i = 1; i < head.length - 1; i++) {
        footRow.push("");
    }
    footRow.push(formatCurrency(totalValue));

    // Draw Table
    autoTable(doc, {
      startY: y + 8, // Standard spacing
      head: [head],
      body: body,
      // Add Footer
      foot: [footRow],
      theme: "striped",
      headStyles: { fillColor: color },
      footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold', halign: 'right' },
      // Align last column right for body and header
      columnStyles: { 
          [head.length - 1]: { halign: "right", fontStyle: "bold" },
          0: { halign: 'left' } // Ensure Total label is left aligned if needed, or let footStyles override
      },
      // Force "Total" label to left align specifically
      didParseCell: function(data) {
          if (data.section === 'foot' && data.column.index === 0) {
              data.cell.styles.halign = 'left';
          }
      },
      margin: { left: margin, right: margin }
    });
    
    y = doc.lastAutoTable.finalY + 15;
  };

  // --- RENDER SECTIONS ---
  if (weekly?.length) {
    const totalWeekly = weekly.reduce((sum, w) => sum + (Number(w.total) || 0), 0);
    const subLabel = frequency === "monthly" ? "Monthly Contributions" : "Weekly Contributions";
    addSection(
        subLabel, 
        ["Member Name", "Amount"], 
        weekly.map(w => [w.memberName, formatCurrency(w.total)]), 
        COLORS.primary,
        totalWeekly
    );
  }

  if (puja?.length) {
    const totalPuja = puja.reduce((sum, p) => sum + (Number(p.total) || 0), 0);
    addSection(
        "Puja Contributions", 
        ["Member Name", "Amount"], 
        puja.map(p => [p.memberName, formatCurrency(p.total)]), 
        COLORS.success,
        totalPuja
    );
  }

  if (donations?.length) {
    const totalDonations = donations.reduce((sum, d) => sum + (Number(d.amount) || 0), 0);
    addSection(
        "Donations", 
        ["Donor", "Date", "Amount"], 
        donations.map(d => [d.donorName, new Date(d.date).toLocaleDateString(), formatCurrency(d.amount)]), 
        COLORS.accent,
        totalDonations
    );
  }

  if (expenses?.length) {
    const totalExpenses = expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);
    addSection(
        "Expenses Breakdown", 
        ["Title", "Date", "Amount"], 
        expenses.map(e => [e.title, new Date(e.date).toLocaleDateString(), formatCurrency(e.amount)]), 
        COLORS.danger,
        totalExpenses
    );
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_History_${sanitizeName(cycle.name)}.pdf`);
};

/* =========================================================
   2. FINANCE EXPORT (Snapshot)
   ========================================================= */
export const exportFinancePDF = ({
  clubName = "Club",
  summary,
  contributions,
  expenses,
}) => {
  const doc = new jsPDF();
  let y = drawHeader(doc, clubName, "Financial Snapshot", "Current Status Overview");

  doc.setFontSize(11); doc.setTextColor(...COLORS.secondary); doc.text("SUMMARY", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Category", "Amount"]],
    body: summary.map((s) => [s.label, formatCurrency(s.value)]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 15;

  // --- CONTRIBUTIONS TABLE ---
  const totalContributions = contributions.reduce((sum, c) => sum + (Number(c.amount) || 0), 0);
  
  doc.text("CONTRIBUTIONS BREAKDOWN", 14, y);
  autoTable(doc, {
    startY: y + 3,
    head: [["Source", "Total Amount"]],
    body: contributions.map((c) => [c.type, formatCurrency(c.amount)]),
    foot: [["Total", formatCurrency(totalContributions)]], // Footer
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } }
  });

  y = doc.lastAutoTable.finalY + 15;

  // --- EXPENSES TABLE ---
  if (expenses?.length) {
    const totalExpenses = expenses.reduce((sum, e) => sum + (Number(e.amount) || 0), 0);

    doc.text("RECENT EXPENSES", 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [["Title", "Status", "Amount"]],
      body: expenses.map((e) => [e.title, e.status.toUpperCase(), formatCurrency(e.amount)]),
      foot: [["Total", "", formatCurrency(totalExpenses)]], // Footer
      theme: "striped",
      headStyles: { fillColor: COLORS.danger },
      footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
      columnStyles: { 2: { halign: "right", fontStyle: "bold" } }
    });
  }

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Finance_Snapshot.pdf`);
};

/* =========================================================
   3. DONATIONS LIST EXPORT
   ========================================================= */
export const exportDonationsPDF = ({ clubName, cycleName, donations = [] }) => {
  const doc = new jsPDF();
  const total = (donations || []).reduce((s, d) => s + Number(d.amount || 0), 0);
  
  let y = drawHeader(doc, clubName, "Donation Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.accent);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Receipt No", "Donor Name", "Contact", "Amount"]],
    body: donations.map((d) => [
      new Date(d.date).toLocaleDateString(),
      d.receiptNo || "-",
      d.donorName || "-",
      d.phone || d.address || "-",
      formatCurrency(d.amount),
    ]),
    // Footer with Total
    foot: [["Total", "", "", "", formatCurrency(total)]],
    theme: "striped",
    headStyles: { fillColor: COLORS.accent },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Donations.pdf`);
};

/* =========================================================
   4. EXPENSES LIST EXPORT
   ========================================================= */
export const exportExpensesPDF = ({ clubName, cycleName, expenses }) => {
  const doc = new jsPDF();
  const totalApproved = expenses
    .filter(e => e.status === "approved")
    .reduce((sum, e) => sum + Number(e.amount || 0), 0);

  let y = drawHeader(doc, clubName, "Expenses Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.danger);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Approved: ${formatCurrency(totalApproved)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Title", "Category", "Recorded By", "Status", "Amount"]],
    body: expenses.map((e) => [
      new Date(e.date).toLocaleDateString(),
      e.title,
      e.category,
      e.recordedBy?.name || "-",
      e.status.toUpperCase(),
      formatCurrency(e.amount),
    ]),
    // Footer with Total
    foot: [["Total", "", "", "", "", formatCurrency(totalApproved)]],
    theme: "striped",
    headStyles: { fillColor: COLORS.danger },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 
        5: { halign: "right", fontStyle: "bold" },
        4: { fontSize: 8, fontStyle: "bold" }
    },
    didParseCell: function(data) {
        if (data.column.index === 4 && data.section === 'body') {
            const status = data.cell.raw;
            if (status === 'APPROVED') data.cell.styles.textColor = [22, 163, 74]; 
            else if (status === 'REJECTED') data.cell.styles.textColor = [220, 38, 38];
            else data.cell.styles.textColor = [217, 119, 6]; 
        }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Expenses.pdf`);
};

/* =========================================================
   5. PUJA CONTRIBUTIONS EXPORT
   ========================================================= */
export const exportPujaPDF = ({ clubName, cycleName, data }) => {
  const doc = new jsPDF();
  const total = data.reduce((sum, row) => sum + Number(row.amount || 0), 0);

  let y = drawHeader(doc, clubName, "Festival Chanda Report", `Cycle: ${cycleName || "N/A"}`);

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.success);
  doc.setFont(undefined, 'bold');
  doc.text(`Total Collected: ${formatCurrency(total)}`, doc.internal.pageSize.width - 14, 35, { align: "right" });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Member Name", "Notes", "Amount"]],
    body: data.map((row) => [
      new Date(row.createdAt).toLocaleDateString(),
      row.user?.name || "Unknown",
      row.notes || "-",
      formatCurrency(row.amount),
    ]),
    // Footer with Total
    foot: [["Total", "", "", formatCurrency(total)]],
    theme: "striped",
    headStyles: { fillColor: COLORS.success },
    footStyles: { fillColor: [241, 245, 249], textColor: COLORS.text, fontStyle: 'bold' },
    columnStyles: { 3: { halign: "right", fontStyle: "bold" } },
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_Puja_Chanda.pdf`);
};

/* =========================================================
   6. MEMBERS LIST EXPORT (NO TOTAL AS REQUESTED)
   ========================================================= */
// ✅ UPDATED FUNCTION: Phone Column Removed
  export const exportMembersPDF = ({ clubName, members, showPhone = false }) => {
    const doc = new jsPDF();
    
    let y = drawHeader(doc, clubName, "Member Directory", `Total Members: ${members.length}`);

    // 1. Dynamic Headers
    const headers = ["#", "Name", "Role"];
    if (showPhone) headers.push("Phone");
    headers.push("Email (User ID)", "Joined");

    // 2. Dynamic Body
    const tableBody = members.map((m, index) => {
      const row = [
        index + 1,
        m.name,
        m.role.toUpperCase(),
      ];
      
      // Only add phone data if flag is true
      if (showPhone) {
        row.push(m.phone || "-");
      }

      row.push(m.email, new Date(m.joinedAt).toLocaleDateString());
      return row;
    });

    autoTable(doc, {
      startY: y,
      head: [headers], 
      body: tableBody,
      theme: "striped",
      headStyles: { fillColor: COLORS.primary },
      columnStyles: { 
        0: { halign: "center", fontStyle: "bold", cellWidth: 10 },
        2: { fontStyle: "bold", fontSize: 8 },
        // Adjust font size if table gets wide
        [showPhone ? 4 : 3]: { fontSize: 9 } 
      },
    });

    drawFooter(doc);
    doc.save(`${sanitizeName(clubName)}_Members_List.pdf`);
  };
/* =========================================================
   7. AUDIT LOGS EXPORT (NO TOTAL AS REQUESTED)
   ========================================================= */
export const exportAuditLogsPDF = ({ clubName, logs, period }) => {
  const doc = new jsPDF();
  
  let y = drawHeader(doc, clubName, "Audit Logs", period ? `Period: ${period}` : "");

  autoTable(doc, {
    startY: y,
    head: [["Date", "Time", "Actor", "Action", "Target", "Details"]],
    body: logs.map((log) => {
        let detailsStr = "-";
        if (log.details) {
             detailsStr = Object.entries(log.details)
                .filter(([k]) => !['_id', 'club', 'userId', 'memberId', 'expenseId'].includes(k))
                .map(([k, v]) => {
                    const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
                    return `${label}: ${v}`;
                })
                .join('\n');
        }

        return [
          new Date(log.createdAt).toLocaleDateString(),
          new Date(log.createdAt).toLocaleTimeString(),
          log.actor?.name || "System",
          log.action?.replace(/_/g, ' ') || "-",
          log.target || "-",
          detailsStr
        ];
    }),
    theme: "grid",
    headStyles: { fillColor: COLORS.secondary }, 
    styles: { fontSize: 8, cellPadding: 2, valign: 'middle' },
    columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 18 },
        2: { cellWidth: 25, fontStyle: "bold" },
        5: { fontSize: 7 }
    }
  });

  drawFooter(doc);
  doc.save(`${sanitizeName(clubName)}_AuditLogs.pdf`);
};